# Generated by Django 4.1.6 on 2023-02-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='created',
        ),
        migrations.RemoveField(
            model_name='home',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='suscribers',
            name='created',
        ),
        migrations.RemoveField(
            model_name='suscribers',
            name='modified',
        ),
        migrations.AddField(
            model_name='home',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AddField(
            model_name='home',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Actualizacion'),
        ),
        migrations.AddField(
            model_name='suscribers',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AddField(
            model_name='suscribers',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Actualizacion'),
        ),
    ]
