# Generated by Django 4.1.6 on 2023-02-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_home_create_at_alter_home_update_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscribers',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo'),
        ),
    ]
