# Generated by Django 4.1.6 on 2023-02-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_suscribers_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscribers',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo'),
        ),
    ]
