# Generated by Django 4.1.6 on 2023-02-14 20:07

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=' ', verbose_name='Contenido'),
            preserve_default=False,
        ),
    ]
