# Generated by Django 4.1.6 on 2023-02-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='favoriteproduct',
            options={'verbose_name': 'Producto Favorito', 'verbose_name_plural': 'Productos Favoritos'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='product',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Disponible'),
        ),
    ]
