# Generated by Django 4.1.6 on 2023-02-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_category_options_alter_favoriteproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='_', editable=False, max_length=300),
            preserve_default=False,
        ),
    ]
