# Generated by Django 4.1.6 on 2023-02-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apellido',
            field=models.CharField(blank=True, max_length=30, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='user',
            name='code_register',
            field=models.CharField(blank=True, max_length=6, verbose_name='Codigo de Registro'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_brth',
            field=models.DateField(blank=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('o', 'Otro')], max_length=1, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=60, verbose_name='Ocupacion'),
        ),
    ]
