# Generated by Django 4.2.6 on 2023-10-10 13:24

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('category', models.CharField(max_length=60, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('service', models.CharField(max_length=60, verbose_name='Servicio')),
                ('resume', models.TextField(max_length=200, verbose_name='Resumen')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Descripcion')),
                ('slug', models.SlugField(editable=False, max_length=300)),
                ('image_1', models.ImageField(null=True, upload_to='servicios', verbose_name='Imagen')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='servicios', verbose_name='Imagen')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='servicios', verbose_name='Imagen')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='servicios', verbose_name='Imagen')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='servicios', verbose_name='Imagen')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.category')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
    ]
