# Generated by Django 4.1.6 on 2023-02-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_servicio_description_servicio_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='resume',
            field=models.TextField(default=' ', max_length=200, verbose_name='Resumen'),
            preserve_default=False,
        ),
    ]
